openapi: 3.1.0
info:
  title: Automatic Speech Recognition (ASR) API
  description: API for using Wav2Vec model in Automatic Speech Recognition (ASR) Inference
  version: "1.0.0"
servers:
  - url: http://localhost:8001
    description: Local development server
paths:
  /asr:
    post:
      summary: Transcribe an uploaded audio file
      description: This endpoint allows you to upload an audio file (MP3) and returns the transcription along with the file's duration.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The audio file to be uploaded (MP3 format only)
      responses:
        '200':
          description: Transcription and duration of the audio file
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcription:
                    type: string
                    description: The transcribed text from the audio file
                  duration:
                    type: string
                    description: The duration of the audio file in seconds
                example:
                  transcription: "BEFORE HE HAD TIME TO ANSWER A MUCH ENCUMBERED VERA BURST INTO THE ROOM"
                  duration: "20.72 seconds"
        '400':
          description: Invalid request (missing file or incorrect file format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Details about the error
                example:
                  detail: "File not provided or file type not supported"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Details about the internal server error
                example:
                  detail: "Error processing file: Unexpected end of file"

  /ping:
    get:
      summary: Health check endpoint
      description: Returns "pong" to check if the service is running.
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "pong"
