elasticsearch_config:
  endpoint_url: https://localhost:9200 # remove `s` in https if xpack.security.http.ssl.enabled = False in docker-compose.yml

elasticsearch_map_type: # Edit this section to change your explicit mapping
  properties:
    filename:
      type: keyword
    generated_text:
      type: text
      analyzer: english
    duration:
      type: float
      coerce: True
    age:
      type: keyword
    gender:
      type: keyword
    accent:
      type: keyword
  
elasticsearch_index:
  name: cv-transcriptions

elasticsearch_map_cols: # Follow the format elastic search col: original data col
  filename: filename
  generated_text: generated_text
  duration: duration
  age: age
  gender: gender
  accent: accent
  

